name: Keep Render Server Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # runs every 5 minutes
  workflow_dispatch:       # optional manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render server
        run: curl -s https://concept-management-backend.onrender.com/
