# name: Keep Render Server Awake

# on:
#   schedule:
#     - cron: '*/10 * * * *'  # runs every 5 minutes
#   workflow_dispatch:       # optional manual trigger

# jobs:
#   ping:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Ping Render server
#         run: curl -s https://conceptmanagement-nextjs.vercel.app/keep-alive


name: Keep Backend Awake (Randomized)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 min, but we'll randomize inside

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Random delay before ping
        run: |
          RANDOM_DELAY=$((RANDOM % 600))  # random 0–600 seconds delay (up to 10 min)
          echo "Sleeping for $RANDOM_DELAY seconds before ping..."
          sleep $RANDOM_DELAY

      - name: Send random URL ping
        run: |
          RANDOM_PARAM=$RANDOM
          echo "Pinging backend with random param..."
          curl -s "https://conceptmanagement-nextjs.vercel.app/keep-alive"
